In [1]:
import numpy as np
import json
from sklearn.neighbors import KDTree

<h1>KD Tree Exploration for Nearest Neighbor</h1>
<br>
<div>In this notebook, we explore the KD Tree data structure, which promises finding nearest neighbors in a k-dimensional space in O(log(n)). First, we explore sklearn.neighbors KDTree class with a random example, then we try to apply it to Dublin Bus stop data.</div>

First, I will examine how KD Trees function with an example of 5 random two-dimensional coordinates

In [2]:
#create random coordinates
np.random.seed(0)
X = np.random.random((5, 2))  # 5 points in 2 dimensions
#pass coordinates to tree
tree = KDTree(X)

In [3]:
#display the coordinates
X

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152]])

In [4]:
#create point that is going to be the pivot point for the search
point=X[0]

In [5]:
point

array([0.5488135 , 0.71518937])

In [6]:
#calculate the 5 nearest neighbor
nearest_dist, nearest_ind = tree.query([point], k=5)

In [7]:
#return the distances
nearest_dist

array([[0.        , 0.14306129, 0.1786471 , 0.20869372, 0.53118409]])

In [8]:
#return the indices of k nearest neighbors, ascending in distance
nearest_ind

array([[0, 2, 1, 3, 4]], dtype=int64)

Next, I will try to apply these learnings to our bus data

In [9]:
with open('all_stops_cleaned.json') as json_file:
    data = json.load(json_file)

In [10]:
coords=np.empty([0,2]) #coordinates will be appended to this array, which will then be used to build KDTree
for row in data:
    coords=np.append(coords,[[row["coords"]["lat"],row["coords"]["lon"]]],axis=0)
coords

array([[53.35224436, -6.26372322],
       [53.35230855, -6.26381074],
       [53.35257451, -6.26417549],
       ...,
       [53.12893197, -6.06280337],
       [53.12880087, -6.06248049],
       [53.18234797, -6.13006416]])

In [11]:
#buil KDTree
tree=KDTree(coords)

In [12]:
#coordinates of "32 Blackhall Pl" in Dublin
test_coords=[53.349160,-6.281690]

In [13]:
#calculate 10 closest stops to test_coords
nearest_dist, nearest_ind = tree.query([test_coords], k=10)

In [14]:
#look at result of KDTree query
nearest_ind

array([[ 950,  987,  988,  951,  986,  853,  952, 1608,  827, 1400]],
      dtype=int64)

In [15]:
#as result above is a two dimensional array, i will have to traverse the inner array at index 0
for ind in nearest_ind[0]:
    print(data[ind])

{'id': '1647', 'name': 'Blackhall Place', 'coords': {'lat': 53.34835106357021, 'lon': -6.282251726202659}}
{'id': '1714', 'name': 'Stoneybatter', 'coords': {'lat': 53.3506378069393, 'lon': -6.28188938800197}}
{'id': '1715', 'name': 'Blackhall Place', 'coords': {'lat': 53.347711982180606, 'lon': -6.28218729951852}}
{'id': '1648', 'name': 'Stoneybatter', 'coords': {'lat': 53.351091367532504, 'lon': -6.28280248510498}}
{'id': '1713', 'name': 'Manor Street', 'coords': {'lat': 53.35190782001921, 'lon': -6.28332547345319}}
{'id': '1476', 'name': 'Sarsfield Quay', 'coords': {'lat': 53.3470736855785, 'lon': -6.28467627539544}}
{'id': '1649', 'name': 'Manor Street', 'coords': {'lat': 53.3525701350153, 'lon': -6.284380448478991}}
{'id': '7453', 'name': 'Arran Quay', 'coords': {'lat': 53.3463358924194, 'lon': -6.27838250402172}}
{'id': '1445', 'name': "Usher's Quay", 'coords': {'lat': 53.345678410254706, 'lon': -6.27828883961715}}
{'id': '4407', 'name': 'Victoria Quay', 'coords': {'lat': 53.34652